
import { Rubik } from "next/font/google";
import Header from "@/components/header.jsx";
import style from '@/styles/Body.module.scss'
import '@/styles/global.css'
import Footer from "@/components/footer";
import ReduxProvider from "@/components/ReduxProvider";
const inter = Rubik({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={style.container}>
          <Header />
          <ReduxProvider>

            {children}
          </ReduxProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
